name = "open-graph-image"
main = "src/index.ts"
compatibility_date = "2022-10-07"
compatibility_flags = ["streams_enable_constructors"]
rules = [
  { type = "Data", globs = ["**/*.ttf", "**/*.otf"], fallthrough = true },
]
